"""Add birth_date

Revision ID: d65a598b5759
Revises: 4c6d990e521f
Create Date: 2025-11-29 17:55:25.368741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd65a598b5759'
down_revision: Union[str, None] = '4c6d990e521f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.alter_column('food_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('food_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('foods', 'spoonacular_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='spoonacular_id::bigint')
    op.alter_column('foods', 'fdc_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='fdc_id::bigint')
    op.drop_index(op.f('ix_journal_entries_user_date'), table_name='journal_entries')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.create_index(op.f('ix_journal_entries_user_date'), 'journal_entries', ['user_id', 'entry_date'], unique=False)
    op.alter_column('foods', 'fdc_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('foods', 'spoonacular_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('food_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('food_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('chat_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_logs_pkey'))
    )
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
